export const FETCHING_BOARDS = 'FETCHING_BOARDS';
export const BOARDS_FETCHED_SUCCESSFULLY = 'BOARDS_FETCHED_SUCCESSFULLY';

export const FETCHING_LISTS = 'FETCHING_LISTS';
export const LISTS_FETCHED_SUCCESSFULLY = 'LISTS_FETCHED_SUCCESSFULLY';
